name: Learning CI

on:
  workflow_dispatch:
    inputs:
      say:
        description: "Text to print"
        required: false
        default: "Hello from manual run!"

jobs:
  basics:
    runs-on: ubuntu-latest
    steps:
      - name: Show event + input
        run: |
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"
          echo "Input say: ${{ inputs.say }}"
